stages:
- image
- mirror

'2.4':
  stage: image
  image: docker:latest
  services:
  - docker:dind
  script: |
    mkdir -p ~/.docker && echo "$DOCKER_AUTH_CONFIG" >~/.docker/config.json
    export suffix=`expr $CI_COMMIT_TAG ':' '2.4-\(.*\)'`
    cd 2.4
    docker build --pull -t ubleipzig/vufind-httpd:2.4 .
    docker push ubleipzig/vufind-httpd:2.4
    for tag in "latest" "2" "2.4-${suffix}"; do
      docker tag ubleipzig/vufind-httpd:2.4 ubleipzig/vufind-httpd:${tag}
      docker push ubleipzig/vufind-httpd:${tag}
    done
  tags:
  - docker
  only:
  - /^2.4/
  except:
  - branches

vufind1:
  stage: image
  image: docker:latest
  services:
  - docker:dind
  script: |
    mkdir -p ~/.docker && echo "$DOCKER_AUTH_CONFIG" >~/.docker/config.json
    export suffix=`expr ${CI_COMMIT_TAG} ':' 'vufind1-2.4-\(.*\)'`
    cd vufind1
    docker build --pull -t ubleipzig/vufind-httpd:vufind1 .
    docker push ubleipzig/vufind-httpd:vufind1
    for tag in "2" "2.4" "2.4-${suffix}"; do
      docker tag ubleipzig/vufind-httpd:vufind1 ubleipzig/vufind-httpd:vufind1-${tag}
      docker push ubleipzig/vufind-httpd:vufind1-${tag}
    done
  tags:
  - docker
  only:
  - /^vufind1-/
  except:
  - branches

github_mirror:
  stage: mirror
  image:
    name: alpine/git
    entrypoint: [ "/bin/sh", "-c" ]
  variables:
    GIT_STRATEGY: clone
    GIT_CHECKOUT: "false"
  script: |
    cd /tmp
    git clone --mirror ${CI_REPOSITORY_URL} project
    cd project
    git remote add github https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/ubleipzig/vufind-httpd.git
    git push --mirror github
  tags:
  - docker
